### ISSUE TITLE
Only save (tryptic) peptides that support a variant

### ISSUE THREAD

**Issue by jgriss** [nf-core/pgdb#12]
@ypriverol When I create a variant DB + the reference I quickly struggle to determine whether the PSMs actually support the specific variant.

My idea would be to create an option to only export (tryptic) peptides that support the specific variant (ie. span the changed AA). Then, one could merge this with the reference (UniProt or other) and quickly see, whether there's support for the variant in question.

What do you think?

**Comment by ypriverol** [comment]
Good Idea. We normally search against the database, whatever is in the variant protein and not in the reference proteome from ensembl we considered variant peptide. 

We probably need to customize more things like missed cleavages etc.

**Comment by jgriss** [comment]
@ypriverol Thanks a lot!

Just for me to understand it correctly: If I include the reference in the database, I get the "original" protein as an entry and the variant protein?

Meaning any peptide uniquely matching to the variant protein is definitely evidence for the changed portion of the protein?

**Comment by husensofteng** [comment]
Hi @jgriss, exactly that is right you if that peptide only matches the variant protein and not any canonical it indicates the peptides is from the variant protein. 

We usually use the protein header that is returned by the search engine to find that out. for instance, when a peptide matches `ENSP` and `var_ENSP` it is labeled as canonical whereas when a peptide only matches a `var_ENSP` then it is surely a variant peptide assuming that the current canonical databases are complete.

The reason we opted out the idea to only keep variant peptides was to avoid pre-selection of the digestion enzyme but maybe we give it another thought in the future.

**Comment by jgriss** [comment]
Hi @husensofteng 

Thanks a lot for the explanation! I think your approach is perfectly fine. I just have to think about how I can best support it in my workflow.

Kind regards,
Johannes
