### ISSUE TITLE
what is the command to get database from COSMIC

### ISSUE THREAD

**Issue by ypriverol** [nf-core/pgdb#3]
Hi @husensofteng : 

@jgriss is interested to generate a database for the following cancer samples: 

https://cancer.sanger.ac.uk/cosmic/browse/tissue?hn=carcinoma&in=t&sh=Merkel_cell_carcinoma&sn=skin&ss=face

**Comment by jgriss** [comment]
Thanks a lot for the help!

**Comment by husensofteng** [comment]
I will get back to this once #4 and #5  are fixed.

**Comment by husensofteng** [comment]
The command to generate a database only for mutations from Merkel_cell_carcinoma in cosmic:

`nextflow main.nf -profile docker  --ensembl_name homo_sapiens --cosmic true --add_reference false --cosmic_user_name your_cosmic_username --cosmic_password your_cosmic_pass --cosmic_cancer_type 'Merkel_cell_carcinoma'
`

**Comment by husensofteng** [comment]
@jgriss could you please check it and remember to input the cosmic account login

**Comment by ypriverol** [comment]
@husensofteng can you add also the cBioPortal part.

**Comment by husensofteng** [comment]
For cbioPortal you need to know what cancer type you want, the command would be:

`nextflow main.nf -profile docker --ensembl_name homo_sapiens --cbioportal true --add_reference false --cbioportal_tissue_type 'cancer_type'
`

**Comment by jgriss** [comment]
Hi @husensofteng @ypriverol 

Thanks a lot!!!

Fasta file was created without a problem. Now I have to wait to see how it affects the actual results. I'll keep you posted!

**Comment by husensofteng** [comment]
I assume the issue is solved so I will close it, please feel free to re-open
