### ISSUE TITLE
Filter cosmic by cell line

### ISSUE THREAD

**Issue by husensofteng** [nf-core/pgdb#4]
## Description of the bug
Filtering on cell names (sample name) is not working. Only mutations from the cell lines listed with --accepted_values should be translated. Running py-pgatk v.0.0.11 as stand alone does produce the right output but within this workflow.

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: 
`nextflow main.nf --ensembl_name homo_sapiens --ncrna false --pseudogenes false --altorfs false --ensembl false --gnomad false --cosmic false --cosmic_celllines true --cbioportal false --decoy false --add_reference false -profile test_full,docker --cosmic_user_name xx@xx --cosmic_password xx  --accepted_values A549`

2. See error: No error

## Expected behaviour

final_proteinDB.fa should only contain 1744 lines but now it contains 2824544 lines (from all cell lines). 

## Log files

Have you provided the following extra information/files:

- [x] The command used to run the pipeline
- [x] [`nextflow.log`](https://github.com/nf-core/pgdb/files/5951437/nextflow.log)

## System

- Hardware: Desktop
- OS: macOS

## Nextflow Installation

- Version: 20.10.0

## Container engine

- Engine: Docker
- version: 20.10.2
- Image tag: nfcore/pgdb:dev

**Comment by husensofteng** [comment]
The same issue happens when filtering cosmic mutations by cancer type:

e.g command:
`nextflow main.nf --ensembl_name homo_sapiens -profile test_full,docker --cosmic true --cosmic_user_name XX --cosmic_password XX --accepted_values lung`

The entire set of mutations are translated rather than just those from lung.

**Comment by husensofteng** [comment]
I think it loads the value `all` for `--accepted_values ` from the config file no matter what is given to the cmd parameter

**Comment by ypriverol** [comment]
Is then a problem in pypgatk?

**Comment by husensofteng** [comment]
`pypgatk` works fine, the issues is with pgdb

**Comment by husensofteng** [comment]
actually, the mistake was in the command line.
instead of giving `--cosmic_cellline_name` I had given `--accepted_values`.
Everything works fine just remember that `--accepted_values` is a parameter in `py-pgatk` not `pgdb` !
