### ISSUE TITLE
Running pgdb with the vcf as an inout

### ISSUE THREAD

**Issue by okendojo** [nf-core/pgdb#8]
I have generated my VCF file. Which command can I use to run this since this is not well captured in the `run your own analysis` section of the pipeline. I am working with the human data.

**Comment by husensofteng** [comment]
the command to only translate a VCF is:

`nextflow run main.nf -profile conda --ensembl_name homo_sapiens --add_reference false --vcf true --vcf_file input_file.vcf`

Please feel free to open the issue if that doesn't work for you

**Comment by okendojo** [comment]
When I run this on my VCF file I get an error below. What could be the problem?

N E X T F L O W  ~  version 20.10.0
Launching `pgdb/main.nf` [serene_knuth] - revision: ed6cf7ffed
[-        ] process > ensembl_fasta_download     -
[-        ] process > gunzip_ensembl_files       -
[-        ] process > add_reference_proteome     -
executor >  local (3)
[a6/642766] process > ensembl_fasta_download     [  0%] 0 of 1
[-        ] process > gunzip_ensembl_files       -
[-        ] process > add_reference_proteome     -
executor >  local (3)
[a6/642766] process > ensembl_fasta_download     [  0%] 0 of 1
[-        ] process > gunzip_ensembl_files       -
[-        ] process > add_reference_proteome     -
executor >  local (4)
[a6/642766] process > ensembl_fasta_download     [100%] 1 of 1 ✔
[6d/a49118] process > gunzip_ensembl_files       [  0%] 0 of 1
[-        ] process > add_reference_proteome     -
[-        ] process > merge_cdnas                -
executor >  local (4)
[a6/642766] process > ensembl_fasta_download     [100%] 1 of 1 ✔
[6d/a49118] process > gunzip_ensembl_files       [100%] 1 of 1, failed: 1 ✘
[-        ] process > add_reference_proteome     -
[-        ] process > merge_cdnas                -
[-        ] process > add_ncrna                  -
executor >  local (4)
[a6/642766] process > ensembl_fasta_download     [100%] 1 of 1 ✔
[6d/a49118] process > gunzip_ensembl_files       [100%] 1 of 1, failed: 1 ✘
[-        ] process > add_reference_proteome     -
[-        ] process > merge_cdnas                -
[-        ] process > add_ncrna                  -
[-        ] process > add_pseudogenes            -
executor >  local (4)
[a6/642766] process > ensembl_fasta_download     [100%] 1 of 1 ✔
[6d/a49118] process > gunzip_ensembl_files       [100%] 1 of 1, failed: 1 ✘
[-        ] process > add_reference_proteome     -
[-        ] process > merge_cdnas                -
[-        ] process > add_ncrna                  -
[-        ] process > add_pseudogenes            -
[-        ] process > add_altorfs                -
[-        ] process > cosmic_download            -
[-        ] process > cosmic_proteindb           -
[-        ] process > cosmic_celllines_proteindb -
[-        ] process > ensembl_vcf_download       -
[-        ] process > gunzip_vcf_ensembl_files   -
[-        ] process > check_ensembl_vcf          -
[-        ] process > ensembl_vcf_proteinDB      -
[-        ] process > gtf_to_fasta               -
[-        ] process > vcf_proteinDB              -
[-        ] process > gencode_download           -
[-        ] process > gnomad_download            -
[-        ] process > extract_gnomad_vcf         -
[-        ] process > gnomad_proteindb           -
[-        ] process > cds_GRCh37_download        -
[-        ] process > download_all_cbioportal    -
[-        ] process > cbioportal_proteindb       -
[-        ] process > merge_proteindbs           -
[-        ] process > clean_protein_database     -
[-        ] process > decoy                      -
[a3/5754d9] process > get_software_versions      [100%] 1 of 1 ✔
[59/4a28fc] process > output_documentation       [100%] 1 of 1 ✔
Execution cancelled -- Finishing pending tasks before exit
-[nf-core/pgdb] Pipeline completed with errors-
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
Error executing process > 'gunzip_ensembl_files'

Caused by:
  Process `gunzip_ensembl_files` terminated with an error exit status (1)

Command executed:

  gunzip -d -f Homo_sapiens.GRCh38.103.gtf.gz Homo_sapiens.GRCh38.cdna.all.fa.gz Homo_sapiens.GRCh38.dna_sm.toplevel.fa.gz Homo_sapiens.GRCh38.ncrna.fa.gz Homo_sapiens.GRCh38.pep.all.fa.gz

Command exit status:
  1

Command output:
  (empty)

Work dir:
  /home/oknjav001/work/6d/a491187bbc383d6fe0eb0da5a754b5

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by ypriverol** [comment]
@javanOkendo can you try now, we have added to the download step a check.

**Comment by okendojo** [comment]
@ypriverol  I will give it a try

**Comment by ypriverol** [comment]
This issue has been fixed and would be replaced by another one @javanOkendo related with the assembly version.
