### ISSUE TITLE
Pipeline alters files in `asset` directory

### ISSUE THREAD

**Issue by jgriss** [nf-core/pgdb#9]
## Issue

When running the pipeline, the `results` directory is created in the `assets` directory. 

(on Linux it's `~/.nextflow/assets/nf-core/pgdb`)

Subsequent calls to the pipeline then fail with the following error:

```
Project `nf-core/pgdb` contains uncommitted changes -- Cannot switch to revision: 7ddf11b
```

## Solution

The `results` directory must no be created in the pipeline's working directory (which seems to remain the `assets` directory) but the users current working directory.

**Comment by jgriss** [comment]
Hi,

And, of course, the output files are also placed in this directory.

**Comment by husensofteng** [comment]
@jgriss that is a weird behaviour!! @ypriverol any suggestions?

**Comment by ypriverol** [comment]
I will have a look

**Comment by ypriverol** [comment]
@jgriss can you try now. We have fixed the output directory.

**Comment by jgriss** [comment]
Fix works. Thanks a lot!
